const menu = [
    {
      id: 1,
      title: 'Yellow Butter Cake',
      category: 'Aniversary',
      price: 500,
      img: './images/item-1.jpg',
      desc: `Many a kid's birthday party is celebrated with a sheet-cake version of this dessert that's topped with billows of chocolate frosting and rainbow sprinkles. `,
    },
    {
      id: 2,
      title: 'Pound Cake',
      category: 'Birthday',
      price: 600,
      img: './images/item-2.jpg',
      desc: `Named because it's made with a pound of each of the main ingredients (flour, butter, and sugar), this cake doesn’t rise much while baking, and the texture is very dense.`,
    },
    {
      id: 3,
      title: 'Red Velvet Cake',
      category: 'Program',
      price: 699,
      img: './images/item-3.jpg',
      desc: `This is a true favorite, especially in the south. Made with either butter or oil, red velvet cake's color classically comes from the reaction of buttermilk and cocoa powder..`,
    },
    {
      id: 4,
      title: 'Carrot Cake',
      category: 'Aniversary',
      price: 999,
      img: './images/item-4.png',
      desc: `Leavened with baking soda and baking powder, this shortened cake uses oil as its main fat rather than butter.`,
    },
    {
      id: 5,
      title: 'Sponge Cake',
      category: 'Birthday',
      price: 599,
      img: './images/item-5.png',
      desc: `This is a foam-style cake that has no artificial leaveners (baking powder or baking soda). `,
    },
    {
      id: 6,
      title: 'Genoise Cake',
      category: 'Program',
      price: 499,
      img: './images/item-6.png',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'Chiffon Cake',
      category: 'Aniversary',
      price: 899,
      img: './images/item-7.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'Flourless Cake',
      category: 'Birthday',
      price: 1299,
      img: './images/item-8.jpg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'Upside Down Cake',
      category: 'Program',
      price: 16.99,
      img: './images/item-9.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;